### ISSUE TITLE
Condense Controllers in Scenes

### ISSUE THREAD

**Issue by krkeegan** [krkeegan/insteon-mqtt#3]
Do we want to ensure that each controller is only specified once?  The following is allowed in the scene code:

```
- controllers:
    - dimmer1
    - keypad1
   responders:
    - fan1
    - fan2

- controllers:
    - keypad1
   responders:
    - fan3
```

I believe everything will work if this is done.  But the import function may do funny things, because when looking to add a responder, it just looks for the first instance of the controller and adds it there (splitting from the other controllers if necessary).  

It isn't a big deal, mostly cosmetic.  I suppose people will only be using 'Import' when first transitioning to insteon-mqtt and probably never again.

Maybe someone will manually create links on the devices and then import them?  This kind of seems like a one off or very rare instance.

Probably don't fix this.
